spring.application.name=tgcapp
spring.config.import=file:env.properties
#--------------------- SERVER CONFIG -------------------------------
server.port=${SERVER_PORT}
#------------------------ DBCONFIG ---------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_NAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
#-------------------- HIBERNATE CONFIG -----------------------------
spring.jpa.hibernate.ddl-auto=update
#-------------------- CLOUDINARY CONFIG ----------------------------
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
#------------------------ JWT CONFIG ------------------------------
jwt.secret=${JWT_SECRET}
#------------------------- MAILGUN --------------------------------
mg.apikey=${MG_API_KEY}
mg.domain=${MG_DOMAIN}}
#------------------------- ADMIN CREDENTIALS -----------------------
admin.firstName=${ADMIN_FIRST_NAME}
admin.lastName=${ADMIN_LAST_NAME}
admin.username=${ADMIN_USERNAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PSWD}
#------------------------- CARD TRADER API_KEY -----------------------
cardtrader.apikey=${CARDTRADER_API_KEY}
